//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odec.CP.Server.Model.Secure.Attachment.Migrations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _201603230938401_InitialSecureContext {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal _201603230938401_InitialSecureContext() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("odec.CP.Server.Model.Secure.Attachment.Migrations.201603230938401_InitialSecureCo" +
                            "ntext", typeof(_201603230938401_InitialSecureContext).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to dbo.
        /// </summary>
        public static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  H4sIAAAAAAAEAO1dbW/cuBH+XqD/YbGf2iLntXNocQ3Wd8g5Tms0b8g6h34L5BVtC6eXPUmbs1H0l/VDf1L/QilRLyQ1JIcSpZVziwMOsUQOOcNnhtTMLOd///nv+oeHKFx8IWkWJPH58uzkdLkg8Tbxg/jufLnPb7/5bvnD97//3frSjx4WP9Xtvi3a0Z5xdr68z/Pdi9Uq296TyMtOomCbJllym59sk2jl+cnq+enpX1dnZytCSSwprcVi/XEf50FEyj/onxdJvCW7fO+FbxOfhFn1nL7ZlFQX77yIZDtvS86XtMH2ZENSOueTsjX9Y7tPycnLPPe29xGJ8xNKLycPebZcvAwDj85xQ8Lb5cKL4yT3csrBi08Z2eRpEt9tdvSBF14/7ghtd+uFGak4e9E2xzJ5+rxgctV2rElt91meRJYEz76tpLaSu/eS/bKRKpXrJZV//lhwXcr2fNlK7wNJoyDLymHkgV9chGnRCbcMEM1nC0TPZw3SKCCL/54t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
