//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odec.CP.Server.Model.Secure.Attachment.Migrations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SecureMigrationScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal SecureMigrationScripts() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("odec.CP.Server.Model.Secure.Attachment.Migrations.SecureMigrationScripts", typeof(SecureMigrationScripts).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  begin tran 
        ///IF  NOT EXISTS (SELECT * FROM sys.objects 
        ///	WHERE object_id = OBJECT_ID(N&apos;[dbo].[AttachmentPermissions]&apos;) AND type in (N&apos;U&apos;))
        ///	begin
        ///		CREATE TABLE [dbo].[AttachmentPermissions] (
        ///			[UserId] [int] NOT NULL,
        ///			[AttachmentId] [int] NOT NULL,
        ///			[PermissionId] [int] NOT NULL,
        ///			[IsOwner] [bit] NOT NULL,
        ///			CONSTRAINT [PK_dbo.AttachmentPermissions] PRIMARY KEY ([UserId], [AttachmentId], [PermissionId])
        ///		)
        ///		
        ///	CREATE INDEX [IX_UserId] ON [dbo].[AttachmentPermissions]([UserId])
        ///	CREAT [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SecureInitial {
            get {
                return ResourceManager.GetString("SecureInitial", resourceCulture);
            }
        }
    }
}
